name: Display Names

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ganti dengan nama file requirements Anda jika diperlukan

    - name: Run Python script
      run: python display_names.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: names_artifact
        path: .  # Mengunggah ke path utama repository

